---
- name: Copy haproxy.cfg template to load balancer node
  template:
    src: haproxy-conf.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    backup: yes
  ignore_errors: false

- name: Copy /etc/default/haproxy template to load balancer node
  template:
    src: default-haproxy.j2
    dest: /etc/default/haproxy
    mode: 0644
    backup: yes
  ignore_errors: false

- name: Copy HAProxy log conf files
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'ansible_haproxy_log', dest: '/etc/rsyslog.d/haproxy.conf' }
    - { src: 'ansible_haproxy_logrotate', dest: '/etc/logrotate.d/haproxy' }

- name: Create log files
  file:
    path: "{{item}}"
    state: touch
    mode: 0644
    owner: haproxy
    group: haproxy
  with_items:
    - /var/log/haproxy.log
    - /var/log/haproxy-status.log

#- name: Restart rsyslog
#  service:
#    name: rsyslog
#    state: restarted
#
#- name: Restart haproxy service
#  service:
#    name: haproxy
#    state: started

#- name: Check haproxy service status
#  shell: systemctl status haproxy --no-pager
#  register: haproxy_status
#- debug:
#    var: haproxy_status.stdout
