---

- name: Copy hosts template to all nodes
  template:
    src: hosts.j2
    dest: /etc/hosts
    backup: yes
    mode: 0644
    owner: root
    group: root
  ignore_errors: false

#- name: Update resolv.conf file
#  lineinfile: "dest=/etc/resolv.conf
#    insertafter=EOF
#    line='nameserver {{dns_server}}'
#    regexp='nameserver {{dns_server}}'
#    state=present"
