---

- name: Copy docker service template to all worker nodes
  template:
    src: docker-service.j2
    dest: /etc/systemd/system/docker.service
    mode: 0644
    backup: yes
  ignore_errors: false

#- name: Get FLANNEL_SUBNET from /run/flannel/subnet.env
#  shell: cat /run/flannel/subnet.env| grep -i FLANNEL_SUBNET|cut -d '=' -f2
#  register: flannel_subnet_env

#- debug:
#    var: flannel_subnet_env.stdout

#- name: Get FLANNEL_MTU from /run/flannel/subnet.env
#  shell: cat /run/flannel/subnet.env| grep -i FLANNEL_MTU|cut -d '=' -f2
#  register: flannel_mtu_env
#- debug:
#    var: flannel_mtu_env.stdout

#- name: Copy docker env file to worker nodes
#  template:
#    src: default-docker.j2
#    dest: /etc/default/docker
#    mode: 0644

- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Start and enable docker service
  service:
    name: docker.service
    state: started
    enabled: yes
  ignore_errors: false

- name: check docker status
  shell: docker version
  become: true
  become_method: sudo
  register: docker_status
  ignore_errors: false

- debug:
    var: docker_status.stdout
