---

- name: Copy 10-gen-kproxy-kubeconfig.j2
  template:
    src: 10-gen-kproxy-kubeconfig.j2
    dest: /k8s-v1.7/certs/gen-kproxy-kubeconfig.sh
    mode: 0744
    owner: kubeuser
    backup: no
  ignore_errors: false

- name: Run gen-kproxy-kubeconfig.sh locally to create kube-proxy kubeconfig
  shell: sh /k8s-v1.7/certs/gen-kproxy-kubeconfig.sh
  ignore_errors: false

- name: Check kube-proxy.kubeconfig files got created
  stat:
    path: /k8s-v1.7/certs/kube-proxy.kubeconfig
  register: kproxy_kubeconfig
  ignore_errors: false

- debug:
    msg: "kube-proxy.kubeconfig file got created."
  when: kproxy_kubeconfig.stat.path is defined
  ignore_errors: false

- fail:
    msg: "Whoops! kube-proxy.kubeconfig file failed to create."
  when: kproxy_kubeconfig.stat.path is not defined
  ignore_errors: false

- name: Delete script gen-kubelet-kubeconfig.sh
  file:
    path: /k8s-v1.7/certs/gen-kproxy-kubeconfig.sh
    state: absent
