---


# In this section we will generate TLS certificates for each Kubernetes component and a client certificate
#for the admin user.

# Create the Admin client certificate

- name: Copy admin-csr file to client machine
  copy:
    src: admin-csr.json
    dest: /k8s-v1.7/certs/
  ignore_errors: false

- name: Generate the admin client certificate and private key "gen-admin-client-cert-key.sh"
  script: gen-admin-client-cert-key.sh
  ignore_errors: false

- name: Verify that admin-key.pem nad admin.pem files got created
  stat:
    path: /k8s-v1.7/certs/admin.pem
  register: admin_cert
  ignore_errors: false

- fail:
    msg: "Whoops! admin-key.pem nad admin.pem file failed to creat."
  when: admin_cert.stat.path is not defined
  ignore_errors: false
