---
#Note: to fix kubectl exec container login issue disable kubelet certs in api service file
#Note: To fix kubectl exec..container login issue
#https://github.com/kelseyhightower/kubernetes-the-hard-way/issues/146
- name: Copy kube-apiserver service template to master nodes
  template:
    src: kube-apiserver.j2
    dest: /etc/systemd/system/kube-apiserver.service
    mode: 0644
    backup: no
  ignore_errors: false

- name: Reload systemd daemon
  command: systemctl daemon-reload
  ignore_errors: false

- name: Start and enable kube-apiserver service
  service:
    name: kube-apiserver
    state: started
    enabled: yes
  retries: 3
  delay: 10
  ignore_errors: false

- name: kube-apiserver services getting started in all master nodes
  wait_for: timeout=10

- name: Check kube-apiserver service status
  shell: systemctl status kube-apiserver --no-pager
  register: api_srv_status
- debug:
    var: api_srv_status.stdout
