---

- name: Do api test through Haproxy
  shell: curl --cacert ~/kubectl-client-setup/ca.pem https://{{KUBERNETES_PUBLIC_ADDRESS}}:{{kube_bind_port}}/version
  register: api_version

- debug:
    var: api_version.stdout
