---

- name: Create etcd directories
  file:
    path: "{{item}}"
    state: directory
    mode: 0755
  with_items:
    - /etc/etcd
    - /var/lib/etcd

- name: Check if etcd package already installed
  stat:
    path: /usr/local/bin/etcd
  register: etcd_file

- name: Download and extract etcd binary
  unarchive:
    src: "{{etcd_pkg}}"
    dest: /tmp
    copy: no
  ignore_errors: false
  when: etcd_file.stat.path is not defined

- name: Copy etcd binaries to /usr/local/bin
  command: "{{item}}"
  with_items:
    -  mv /tmp/etcd-v3.2.6-linux-amd64/etcd /usr/local/bin/
    -  mv /tmp/etcd-v3.2.6-linux-amd64/etcdctl /usr/local/bin/

- name: Check required etcd binaries got created
  stat:
    path: /usr/local/bin/etcdctl
  register: etcdctl
  ignore_errors: false

- fail:
    msg: "Whoops! ectd binaries are missing."
  when: etcdctl.stat.path is not defined
  ignore_errors: false

- name: Remove /tmp/etcd additional data
  file:
    path: /tmp/etcd-v3.1.4-linux-amd64
    state: absent
