---

- name: Create a busybox deployment
  shell: kubectl run busybox --image=busybox --command -- sleep 3600
  retries: 3
  delay: 10
  register: busybox_pod
  ignore_errors: true

- name: Get created busybox pod name
  shell: kubectl get pods -l run=busybox -o jsonpath="{.items[0].metadata.name}"
  register: box_pod_name
  when:  busybox_pod | succeeded

  ignore_errors: true
- debug:
    var: box_pod_name.stdout

- name: Execute a DNS lookup for the kubernetes service inside the busybox pod
  shell: kubectl exec -ti {{box_pod_name.stdout}} -- nslookup kubernetes
  register: dns_test
  when: box_pod_name | succeeded
- debug:
    var: dns_test.stdout
  when: dns_test | succeeded

- name: Delete busybox deployment
  shell: kubectl delete deployment busybox
  when: dns_test | succeeded
